// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/projects.tsx";
import * as $$0 from "./islands/Card.tsx";
import * as $$1 from "./islands/Footer.tsx";
import * as $$2 from "./islands/Header.tsx";
import * as $$3 from "./islands/Issues.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/projects.tsx": $3,
  },
  islands: {
    "./islands/Card.tsx": $$0,
    "./islands/Footer.tsx": $$1,
    "./islands/Header.tsx": $$2,
    "./islands/Issues.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
